# Generated by Django 3.1.7 on 2021-03-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guardia',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='medico',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='guardia',
            name='medico',
            field=models.ForeignKey(blank=True, default='Sin médico asignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agenda.medico'),
        ),
    ]
