# Generated by Django 3.1.7 on 2021-03-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_auto_20210329_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
