# Generated by Django 3.1.7 on 2021-03-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_auto_20210329_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardia',
            name='usuario',
        ),
    ]
