# Generated by Django 3.1.7 on 2021-03-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_remove_guardia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='departamento',
            field=models.CharField(choices=[('S/A', 'S/A'), ('Artigas', 'Artigas'), ('Canelones', 'Canelones'), ('Cerro Largo', 'Cerro Largo'), ('Colonia', 'Colonia'), ('Durazno', 'Durazno'), ('Flores', 'Flores'), ('Florida', 'Florida'), ('Lavalleja', 'Lavalleja'), ('Maldonado', 'Maldonado'), ('Montevideo', 'Montevideo'), ('Paysandu', 'Paysandu'), ('Rio Negro', 'Rio Negro'), ('Rivera', 'Rivera'), ('Rocha', 'Rocha'), ('Salto', 'Salto'), ('San José', 'San José'), ('Tacuarembó', 'Tacuarembó'), ('Treinta y Trees', 'Treinta y Tres')], default='S/A', max_length=20),
        ),
    ]
