# Generated by Django 3.1.7 on 2021-03-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0006_auto_20210329_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='medico',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agenda.medico'),
        ),
    ]
