# Generated by Django 3.1.7 on 2021-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0007_auto_20210329_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='min_ranking',
            field=models.BigIntegerField(default=1),
        ),
    ]
