# Generated by Django 3.1.7 on 2021-04-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0012_auto_20210412_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='imagen',
        ),
    ]
